# Generated by Django 2.2 on 2021-05-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ducktrading_test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='users',
        ),
    ]
