# Generated by Django 2.2 on 2021-05-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducktrading_test_app', '0003_auto_20210516_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
