# Generated by Django 2.2 on 2021-05-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducktrading_test_app', '0004_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
