# Generated by Django 2.2 on 2021-05-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducktrading_test_app', '0006_auto_20210517_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
