# Generated by Django 2.2 on 2021-05-18 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ducktrading_test_app', '0007_auto_20210517_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ducktrading_test_app.User'),
            preserve_default=False,
        ),
    ]
